apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
    name: common-placementrules-two
    namespace: common-policies
spec:
    clusterSelector:
        matchExpressions:
            - key: common-two
              operator: In
              values:
                - "true"
